# Generated by Django 4.2.8 on 2023-12-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverManagement', '0002_delete_driverinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=200)),
                ('numberOfDrowsiness', models.CharField(max_length=200)),
                ('numberOfPhoneUsage', models.CharField(max_length=200)),
                ('numberOfWorkingDay', models.IntegerField(default=0)),
                ('numberOfRuleViolation', models.CharField(max_length=200)),
                ('numberOfTrafficViolation', models.IntegerField(default=0)),
                ('drivingLicenseExpiredDate', models.DateTimeField(default=0)),
                ('firstLogInTime', models.DateTimeField(default=0)),
                ('lastOnlineTime', models.DateTimeField(default=0)),
                ('drivingDuration', models.IntegerField(default=0)),
            ],
        ),
    ]
